APP_NAME_DEFAULT = "FastAPI Template"
APP_ENV_DEFAULT = "local"
APP_DEBUG_DEFAULT = False
API_V1_PREFIX_DEFAULT = "/api/v1"
APP_VERSION_DEFAULT = "0.1.0"
LOCAL_LOG_LEVEL_DEFAULT = "DEBUG"
DEFAULT_LOG_LEVEL = "INFO"
DEFAULT_LOG_JSON = True

DEFAULT_CORS_ALLOW_ORIGINS = "http://localhost:3000,http://127.0.0.1:3000"
DEFAULT_CORS_ALLOW_CREDENTIALS = True
DEFAULT_CORS_ALLOW_METHODS = "GET,POST,PUT,PATCH,DELETE,OPTIONS"
DEFAULT_CORS_ALLOW_HEADERS = "Authorization,Content-Type"

JWT_ALGORITHM = "HS256"

DEFAULT_ADMIN_FULL_NAME = "Aditi Sharma"

EXAMPLE_USER_FULL_NAME = "Priya Sharma"
EXAMPLE_USER_EMAIL = "priya.sharma@example.com"
EXAMPLE_ADMIN_EMAIL = "aditi.admin@example.com"
EXAMPLE_STRONG_PASSWORD = "StrongPassword123!"
